### ISSUE TITLE
Missed the shot with Book Token

### ISSUE THREAD

**Issue by htlorenzen** [Alkaar/resy-booking-bot#119]
I have been testing my bot after getting it setup. I have read other closed threads with this same issue, and made the proper changes, but still no success (on venues with open slots). My bot gets to the point where it sees the reservation and attempts to book it, provides a book token, and still says it misses the shot. Other users said to add a header for both the get and post commands, which I have already done. Are there any other issues that could be causing this?

**Comment by Alkaar** [comment]
I just pushed a fix 👉 https://github.com/Alkaar/resy-booking-bot/pull/122. Seems like the Referer header is now required as well.

**Comment by draconics37** [comment]
I'm still running into the same issue even after pulling in this new change (confirming even after recloning), even after triple checking (1) both authorization parameters, (2) the venue ID, and (3) that there exists open reservations for the selected date/times. It's showing me the same pattern of output described in this issue, with the bot showing a book token and still showing a Missed the shot/Reservation no longer available error. Please let me know if there's anything else I should check on here configuration-wise, or if some other fix is required here.

Edit: seems like this has already been flagged at #120

**Comment by Alkaar** [comment]
Going to close this out and have everyone follow https://github.com/Alkaar/resy-booking-bot/issues/120 for continued discussions
